### ISSUE TITLE
Be able to post videos to Youtube, Farcaster and X

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#632] opened 2024-06-18 10:58 UTC
Related to #634

**Comment by Mario-SO** [comment] 2024-07-02 12:14
I created a different issue for each platform

Lens: #706 
Farcaster: #705 
YouTube: #704 
X: #703 

Please @Eric-Vondee, take responsibility on uploading the state of current development of X by checking the checkboxes.
@greatsamist do the same for YouTube.

**Comment by xannyxs** [comment] 2024-07-08 07:57
Duplicate of #735 #734 #733 #732

**Closed by xannyxs** 2024-07-08 07:57 UTC
Labels: enhancement
