### ISSUE TITLE
[BUG] Proposal to Fix Critical Bug with Image Uploads

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#629] opened 2024-06-16 11:39 UTC
**Current Issue:**
When a user uploads an image named "anImage.png" and another user subsequently uploads a different image with the same name, the system does not upload the new image. Instead, it uses the image uploaded by the first user.

**Proposed Solution:**
To avoid this conflict, we should use a unique identifier, such as the session or stage ID, instead of relying on `file.name`.

**Challenges:**
We need a strategy to handle legacy images that are currently identified by their file names.

**Steps to Reproduce:**
1. User A uploads an image named "anImage.png".
2. User B uploads a different image with the same name "anImage.png".
3. Observe that the second image is not uploaded and the first image is used instead.

**Expected Behaviour:**
Each image upload should be uniquely identified to avoid conflicts, ensuring that different images with the same file name do not overwrite each other.

**Additional Notes:**
- Consider implementing a migration plan for existing images to align with the new identification strategy.

**Comment by Mario-SO** [comment] 2024-06-17 15:27
Thanks Xander for doing this, great job. It is also important to (if you know who) assign it to someone from the beginning, also select a project where this belongs to.

Adding screenshots to the issue is also helpful. Once I have access to the repo I will edit the templates and stuff to make space for this kind of things.

Again, thanks for the effort.

**Comment by Mario-SO** [comment] 2024-06-18 11:28
Will close due to fix by @Eric-Vondee

**Closed** 2024-07-04 13:07 UTC
Labels: bug
